apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterbuilders.kpack.io
spec:
  group: kpack.io
  version: v1alpha1
  names:
    kind: ClusterBuilder
    singular: clusterbuilder
    plural: clusterbuilders
    shortNames:
    - ccb
    - customclusterbuilders
    - customclusterbuilder
    categories:
    - kpack
  scope: Cluster
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: LatestImage
    type: string
    JSONPath: ".status.latestImage"
  - name: Ready
    type: string
    JSONPath: #@ ".status.conditions[?(@.type==\"Ready\")].status"