apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: customclusterbuilders.kpack.io
spec:
  group: kpack.io
  version: v1alpha1
  names:
    kind: CustomClusterBuilder
    singular: customclusterbuilder
    plural: customclusterbuilders
    shortNames:
    - ccb
    categories:
    - kpack
  scope: Cluster
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: LatestImage
    type: string
    JSONPath: ".status.latestImage"
  - name: Ready
    type: string
    JSONPath: #@ ".status.conditions[?(@.type==\"Ready\")].status"