apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterstacks.kpack.io
spec:
  group: kpack.io
  version: v1alpha1
  names:
    kind: ClusterStack
    singular: clusterstack
    plural: clusterstacks
    categories:
    - kpack
  scope: Cluster
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Ready
    type: string
    JSONPath: #@ ".status.conditions[?(@.type==\"Ready\")].status"
